Enable optional SSL on Postgres server
- Remove references to tag property in databases and roles
- Provide script for generating SSL certificates

[#146008833]

Signed-off-by: Steffen Uhlig <Steffen.Uhlig@de.ibm.com>

diff --git a/scripts/generate-pgats-manifest-v2 b/scripts/generate-pgats-manifest-v2
--- a/scripts/generate-pgats-manifest-v2
+++ b/scripts/generate-pgats-manifest-v2
@@ -10,22 +10,31 @@ SYNOPSIS:
     Generate a bosh v2 manifest for a postgres-release acceptance test errand job deployment.
 
 USAGE:
-    $0 -p <property-path>
+    $0 -v <path-to-variable-file> [ -o <path-to-operations-file> -b <bosh-cli-v2-alias> ]
 
 MANDATORY ARGUMENTS:
-    -p <property-path>         Path to property-overrides stub file.
-	                           You can use it to override deployment name or
-							   cloud-config reference.
+    -v <path-to-variable-file>   Path to variables file containing BOSH director url, user, password, and ca certificate. See by way of example 'manifest/v2/bosh-lite/pgats-vars.yml'.
 
+OPTIONAL ARGUMENTS:
+    -o <path-to-operations-file> Path to operation file. You can use it to customize properties (see by way of example 'templates/v2/operations/pgats-props.yml').
+    -b <bosh-cli-v2-alias>          Specify the bosh cli v2 if different from 'bosh'.
 
 EOF
   exit 1
 }
 
-while getopts "p:" opt; do
+boshcli=bosh
+
+while getopts "v:o:b:" opt; do
   case $opt in
-    p)
-      property_overrides=$OPTARG
+    o)
+      operations_file="--ops-file ${OPTARG}"
+      ;;
+    v)
+      variables_file="--vars-file=${OPTARG}"
+      ;;
+    b)
+      boshcli=${OPTARG}
       ;;
     *)
       echo "Unknown arguments"
@@ -34,18 +43,11 @@ while getopts "p:" opt; do
   esac
 done
 
-if [ -z ${property_overrides} ]; then
-  >&2 echo "ERROR: Property-overrides stub file is missing"
-  argument_error=true
-
-else
-  if [ ! -f "${property_overrides}" ]; then
-    >&2 echo "ERROR: Property-overrides stub '${property_overrides}' is not a regular file"
-    argument_error=true
-  fi
+if [ -z ${variables_file} ]; then
+  >&2 echo "ERROR: variables file is missing"
+  exit 1
 fi
 
-spiff merge \
-  ${manifest_dir}/generic-manifest-mask.yml \
-  ${manifest_dir}/pgats-errand.yml \
-  ${property_overrides}
+${boshcli} interpolate ${manifest_dir}/pgats-errand.yml \
+  ${variables_file} \
+  ${operations_file}
